services:
  telegram-bot:
    build: .
    container_name: nu_sho_ti_golova_bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CHAT_ID=${CHAT_ID}
      - DB_PATH=${DB_PATH:-bot_database.db}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge